#import "../lib/conf.typ": conf
#import "../lib/templates.typ": *

// Initial Config
#let name = "Group Theory"
#let sname = "With Okron's Templates"
#let authors = (
    (
      name: "Ain Bolaños Cortés",
      affiliation: "Universidad Panamericana", 
      email: "ain.bc@proton.me",
    ),
)
#let abstract = []

// Set functions
#set document(
  date: auto,
  title: [#name],
)

#show: conf.with(
  title: [#name],
  subtitle: [#sname],
  authors: authors,
  abstract: abstract,
)
#show: counter_conf

// Main document
= Introduction

#note[
  All counters (Theorem, Definition, Proposition, etc.) are automatically
  reset at each section heading (level 1).
]

== Group Initiation

#def("Group")[
  A *group* is an ordered pair $(G, *)$ where $G$ is a set and
  $* : G times G -> G$ is a binary operation such that:
  1. *Associativity:* $(a * b) * c = a * (b * c)$ for all $a,b,c in G$.
  2. *Identity:* There exists $e in G$ such that $a * e = e * a = a$ for all $a in G$.
  3. *Inverse:* For each $a in G$ there exists $a^{-1} in G$ with $a * a^{-1} = a^{-1} * a = e$.
]

With the previous definition we are now able to make some observations, as the following:

#prop("Uniqueness of identity and inverses")[
  In a group $(G, *)$ the identity element is unique, and every element has a unique inverse.
]

And also we can talk about Lemmas.

#lem("Powers in a group")[
  For any $a in G$ and $m,n in ZZ$, we have $a^m a^n = a^(m+n)$ and $(a^m)^n = a^(m n)$,
  where $a^k$ is defined recursively.
]

Finally it may be useful to write some Affirmations.

#af("Left and right cancellation")[
  In a group, $a b = a c$ implies $b = c$, and $b a = c a$ implies $b = c$.
]

#lorem(40)

#lorem(40)
#pagebreak()


= Theorems and Proofs

#thm("Lagrange's Theorem", [
  If $G$ is a finite group and $H <= G$ a subgroup, then $|H|$ divides $|G|$.
  In particular, $|G| = [G:H] ,|H|$.
])

#cor("Order of an element")[
  For any element $g in G$ of finite order, $|g|$ divides $|G|$.
]

#proof[
  Let $n = |g|$ and let $H = chevron.l g chevron.r$ be the cyclic subgroup generated by $g$.
  Then $|H| = n$. By Lagrange’s theorem $n$ divides $|G|$.
]

#rmk[
  The converse of Lagrange’s theorem does not hold in general. For example,
  $A_4$ has order $12$ but has no subgroup of order $6$.
]
#pagebreak()


= Examples and Exercises

#ej("Cyclic group", [
  The group $ZZ_n$ under addition modulo $n$ is cyclic. Every subgroup of a
  cyclic group is also cyclic.
])

#ex("A non‑abelian group", [
  Show that the symmetric group $S_3$ is not abelian.
])

#proof[
  $S_3$ consists of permutations of three elements. Compute $(1 2)(1 3) = (1 3 2)$
  but $(1 3)(1 2) = (1 2 3)$. Since $(1 3 2) != (1 2 3)$, the group is non‑abelian.
]

#ex("Subgroup test", [
  Prove that a non‑empty subset $H subset.eq G$ is a subgroup iff $a b^(-1) in H$
  whenever $a,b in H$.
])

#pagebreak()


= Figures, Code and Plots
\
#graf("../example/src/img/profile.png", caption: [The best profile picture ever.], width: 20%)
If the image is missing, you can still see the figure structure.

#let sample_code = "
def multiply(a, b):
     return a * b
 
 result = multiply(3, 5)
 print(f\"3 * 5 = {result}\")
"
#code("Python Multiplication", output: "3 * 5 = 15", sample_code)

This is a practical way to include code snipets on your writings.
